apiVersion: apps/v1
kind: Deployment
metadata: 
 name: healthcare
spec:
 replicas: 1
 selector:
  matchLabels:
  app: healthcare
 template:
 metadate:
 lables:
 app: healthcare
spec:
containers:
-name: healthcare
image: frost113/hraltcare-buvan3:3
ports:
 -containersPort: 8082

---
apiVersion: v1
kind: Service
metadata:
 name: healtcare
 spec:
 selector:
 app: healthcare
 type: Nodeport
 ports: 
 -port: 80
 targetPort: 8082
 nodePort: 30007

