kind: Deployment
apiVersion: apps/v1
metadata:
 name: healthcare
spec:
 replicas: 1
 selector:
 matchLabels:
 name: healthcare
 template:
 metadata:
 name: testp1
 labels:
 name: healthcare
 spec:
 containers:
 - name: simple-container
 image: frost113/hraltcare-buvan3:3
 ports:
 - containerPort: 8082
---
kind: Service
apiVersion: v1
metadata:
 name: healthcare
spec:
 ports:
 - port: 80
 targetPort: 8082 
 nodePort: 30007
 selector:
 name: healthcare 
 type: NodePort
